### PR TITLE
Quite some updates

### PR DESCRIPTION
**Pull request by wztzjhn**
Hi Kip, 
This pull request includes various changes accumulated over the years -- sorry I did not think in advance and separate them into a few clear and self-revealing features. However, as both compiler (c++ and nvcc) and hardware evolves, it is easier just to push these changes rather than leaving them behind, otherwise the codes just do not compile on the master branch. Also, as you mentioned at some point, we can also initiate an ownership transfer of the kondo project if you see proper.

Cheers,
Zhentao

### CODE REVIEW

**Comment by kbarros** [comment]
Hi Zhentao, I'd be happy to transfer ownership of this repository. When I tried, I got the error "Repository wztzjhn/Kondo already exists". I think a formal transfer would be good because it keeps all the Github repo metadata: Issues/PRs/Comments, etc. Maybe if you rename your current repository to `Kondo_forked` it will let me transfer this one?

**Comment by wztzjhn** [comment]
Thanks! I have just renamed my fork as Kondo_forked as you suggested.

**Comment by kbarros** [comment]
Hi Zhentao, I'm still unable to transfer. Apparently it won't be possible as long as a "fork" exists in your `wztzjhn` organization. Could you please try following the steps outlined in this post: https://www.reddit.com/r/github/comments/1domyzj/what_are_possible_reasons_why_i_cant_transfer_a/
Basically, you need to remove the fork from Github before I can transfer ownership of the original to you.

**Comment by wztzjhn** [comment]
Hi Kip, the fork has been deleted. Hopefully it should work finally :)

**Comment by wztzjhn** [comment]
The transfer worked! @kbarros

**Pull request closed without merging**
